openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for gophermart
paths:
    /api/:
        get:
            tags:
                - MyService
            summary: Method MyService
            operationId: MyService#Method
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            example: Provident vel qui occaecati voluptates.
                        example: Dolor et sunt rem occaecati rerum enim.
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'bad_request: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomError'
                            example:
                                message: Sed aperiam omnis placeat et quia velit.
                                name: Voluptas sit.
                                occurred_at: "1976-11-16T10:53:37Z"
                "500":
                    description: 'internal_error: Internal Server Error response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomError'
                            example:
                                message: Quas minus ab ex.
                                name: Quam ut.
                                occurred_at: "1997-04-23T16:42:19Z"
    /api/api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginPass'
                        example:
                            login: Enim magnam odit accusamus laborum ipsam.
                            password: Sed repellat temporibus.
            responses:
                "200":
                    description: OK response.
    /api/api/user/orders:
        post:
            tags:
                - balance
            summary: post order balance
            operationId: balance#post order
            responses:
                "200":
                    description: The order number has already been uploaded by this user.
                "202":
                    description: The new order number has been processed.
                "400":
                    description: 'badRequest: Bad Request response.'
                    content:
                        application/json:
                            example:
                                name: Sit asperiores consequuntur earum ut.
                "401":
                    description: User is not authenticated
                "409":
                    description: The order number has already been uploaded by another user
                "422":
                    description: Invalid order number format.
                "500":
                    description: Internal server error
    /api/api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginPass'
                        example:
                            login: Voluptate et.
                            password: Maxime sequi qui accusamus aperiam rem.
            responses:
                "200":
                    description: OK response.
components:
    schemas:
        CustomError:
            type: object
            properties:
                message:
                    type: string
                    description: Message of error.
                    example: Modi qui ea.
                name:
                    type: string
                    description: Name of error.
                    example: Qui earum ab.
                occurred_at:
                    type: string
                    description: Time error occurred.
                    example: "2010-08-23T22:22:06Z"
                    format: date-time
            example:
                message: Placeat consectetur harum ea.
                name: Tempora nihil rerum quod.
                occurred_at: "2001-02-07T18:33:13Z"
            required:
                - name
                - message
                - occurred_at
        LoginPass:
            type: object
            properties:
                login:
                    type: string
                    example: Laudantium dolorem.
                password:
                    type: string
                    example: Quod quia expedita maiores.
            example:
                login: Nam ullam error et saepe.
                password: Adipisci alias molestiae qui voluptas inventore id.
            required:
                - login
                - password
        OggophermartError:
            type: object
            properties:
                name:
                    type: string
                    description: identifier to map an error to HTTP status codes
                    example: Dolor sit et inventore possimus quis velit.
            example:
                name: At architecto.
            required:
                - name
        PostOrderResult:
            type: object
        UserServiceResult:
            type: object
            example: {}
tags:
    - name: MyService
    - name: user
    - name: balance
